from api import login
from api import profile
from api import homework
from api import leave
from api import schedule_teacher
from api import calendar
from api import list_hw
from api import score
from api import update_score
from api import update_grade
